controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true
  
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - front_left_steering
      - front_right_steering


velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - front_left_spinning
      - front_right_spinning
      - back_left_spinning
      - back_right_spinning