controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
  
  position_controller:
    type: position_controllers/JointGroupPositionController

  velocity_controller:
    type: velocity_controllers/JointVelocityPositionController

  joint_state_broadcaster:
    type: joint_state_broadcaster/JointStateBroadcaster


position_controller:
  ros__parameters:
    joints:
      - front_left_steering
      - front_right_steering


velocity_controller:
  ros__parameters:
    joints:
      - back_left_spinning
      - back_right_spinning